# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  Build-all:
    cmds:
      - bash collect.sh
  Build:QuestBondCalculator:
    cmds:
      - bash update_questbondcalculator.sh
  Build:FreeQuestDataViewer:
    cmds:
      - bash update_freequestdataviewer.sh
  Build:ChaldeaViewer:
    cmds:
      - bash update_chaldeaviewer.sh
